### PR TITLE
Oak-D producer test

### PR DESCRIPTION
**Pull request by tristanle22**
Wrote a quick Oak-D producer test. Haven't tested if it works on the Oak-D
- There are 2 states: 'idle' -> do nothing, 'produce' -> produce frame from the Oak-D
- How to set state: just send 'idle' or 'produce' as a message to the server
- Make sure to modify the host address and port
- How to run: python3 producer_test_oakd.py

### CODE REVIEW

**Comment by SyedShayaan** [comment]
Sounds good.

**Review by SyedShayaan — CHANGES_REQUESTED** [review]
Can you look at my implementation of the simple webserver, cam_websocket.py, located inside viso-frontend/Viso (livestreamCam branch), and add in the compression and encoding steps to the websocket server you have made.

**Comment by tristanle22** [comment]
@SyedShayaan ok done, lmk if it works.

**Comment by SyedShayaan** [comment]
good to merge

**Review by SyedShayaan — APPROVED** [review]

**Pull request merged**
